### ISSUE TITLE
Tom Petch's WG adoption comments

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/ietf-ccamp-otn-path-computation#8]
> I do not have a problem with the WG doing this work but think that the approach is going to confuse and mislead.
> 
> The content of this started life elsewhere, under a different name, and I can see nothing in the I-D or in the datatracker to record this history.  I have seen ADs fail to understand that there has been a name change and go off on the wrong track as a result.
> 
> I think that both the otn and the optical I-D need statements in them about this history.
> 
> I think also that this is one of those rare cases when changing the name on adoption would be a good thing, not so much for this I-D as for draft-gbb-optical-path-computation-yang which is materially different from its precursor.

Authors>> TBD

See: https://mailarchive.ietf.org/arch/msg/ccamp/ygSbuE0XIJkq0JgpUY7k1VRdhak/

**Comment by italobusi** [comment]
Proposal from Daniel and Daniele shared on the list:

> Maybe the I-D authors could add an appendix with a change log describing the
> reasoning behind the split, and a note suggesting the appendix is removed
> before publication. It would clearly show the history and reason for the
> split without requiring an entry in the datatracker. 

See: https://mailarchive.ietf.org/arch/msg/ccamp/BmKmv2Dri-mcHf_LzkM9lzsE_c8/

> The appendix sounds great. That would solve the issue and won't cause any problem with the Datatracker.
> 
> You can introduce it in the WG -00 version as it's not changing the content of the draft.

See: https://mailarchive.ietf.org/arch/msg/ccamp/bwtywOs8IJ6idI0YabzUPLjIHZo/

**Comment by italobusi** [comment]
- [x] @danielkinguk : provide a text proposal for the appendix text

**Comment by danielkinguk** [comment]
Appendix A. Change Log 

The initial YANG data model requesting path computation in optical networks was draft-gbb-ccamp-optical-path-computation-yang-00. This document included path computation request capabilities for WSON, Flexi-Grid and OTN technologies. However, it was proposed at IETF 113 (March 25, 2022) to split the initial document into separate documents for WDM (WSON and Flexi-Grid) and OTN technologies, as each technology may be developed and implemented separately.  

The WDM technology capabilities were kept in [draft-gbb-ccamp-optical-path-computation-yang], and the OTN capabilities were moved into a new document [draft-gbb-ccamp-otn-path-computation-yang].  

Editors note, please remove this appendix before publication.
